name: Update README with my latest coding stats

on:
  schedule:
    - cron: '30 5 * * *'
  workflow_dispatch:

jobs:
  update-Readme:
    name: Automatically update my README  
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_TITLE: true
          BLOCKS: ->
          TIME_RANGE: last_30_days
          SHOW_TIME: true
          SHOW_MASKED_TIME: true
